/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PatternOp = {
  type: string;
  [k: string]: unknown;
} & PatternOp1;
export type PatternOp1 =
  | {
      type?: "Wait";
      ticks: number | string;
      [k: string]: unknown;
    }
  | {
      type?: "Fire";
      projectile: string;
      angle?: number | string;
      speed?: number | string;
      [k: string]: unknown;
    }
  | {
      type?: "FireRing";
      projectile: string;
      count: number | string;
      speed?: number | string;
      radius?: number | string;
      [k: string]: unknown;
    }
  | {
      type?: "FireArc";
      projectile: string;
      count: number | string;
      spread: number | string;
      direction: number | string;
      speed?: number | string;
      [k: string]: unknown;
    }
  | {
      type?: "Loop";
      count: number | string;
      ops: PatternOp[];
      [k: string]: unknown;
    }
  | {
      type?: "SpawnSubpattern";
      patternId: string;
      [k: string]: unknown;
    }
  | {
      type?: "Set";
      param: string;
      value: number | string;
      [k: string]: unknown;
    };

export interface Pattern {
  id: string;
  params?: {
    [k: string]: number;
  };
  ops: PatternOp[];
  [k: string]: unknown;
}
