/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Projectile {
  id: string;
  sprite: string;
  hitboxRadius: number;
  damage?: number;
  movement?: Movement;
  [k: string]: unknown;
}
export interface Movement {
  type: "Linear" | "Accelerating" | "Homing";
  acceleration?: number;
  maxSpeed?: number;
  turnRate?: number;
  [k: string]: unknown;
}
