/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SequenceOp = {
  type: string;
  [k: string]: unknown;
} & SequenceOp1;
export type SequenceOp1 =
  | {
      type?: "StartPattern";
      patternId: string;
      slot?: string;
      [k: string]: unknown;
    }
  | {
      type?: "StopPattern";
      slot: string;
      [k: string]: unknown;
    }
  | {
      type?: "MoveToPath";
      pathId: string;
      duration: number | string;
      [k: string]: unknown;
    }
  | {
      type?: "SetParam";
      slot?: string;
      param: string;
      value: number | string;
      [k: string]: unknown;
    }
  | {
      type?: "ClearBullets";
      radius?: number | string;
      convertToDrop?: boolean;
      [k: string]: unknown;
    }
  | {
      type?: "PhaseTransition";
      hpPercent: number;
      ops: SequenceOp[];
      [k: string]: unknown;
    }
  | {
      type?: "SpawnDrop";
      dropId: string;
      count?: number | string;
      [k: string]: unknown;
    }
  | {
      type?: "Wait";
      ticks: number | string;
      [k: string]: unknown;
    };

export interface Sequence {
  id: string;
  ops: SequenceOp[];
  [k: string]: unknown;
}
